
development:
  adapter: postgresql
  encoding: unicode
  database: airline_cargo_broker
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: airline_cargo_broker
  pool: 5
  username: postgres
  password: postgres